In [1]:
import numpy as np

In [26]:
shape = [4, 4]

## Матрица

In [142]:
matrix = (np.random.random(size=shape) * 10).astype(np.int)
print(matrix)

[[4 1 7 9]
 [6 0 9 6]
 [5 2 4 2]
 [4 6 7 5]]


In [123]:
matrix = np.array([[1, 2, 2, 1],
                   [7, 1, 1, 9],
                   [8, 1, 1, 5],
                   [0, 1, 1, 0]])
print(matrix)

[[1 2 2 1]
 [7 1 1 9]
 [8 1 1 5]
 [0 1 1 0]]


## Проверка на невырожденность

In [143]:
print(f'Определитель матрицы = {np.linalg.det(matrix):5.4f}')
print(f'Матрица {"не " if np.linalg.det(matrix) != 0 else " "}вырождена')

Определитель матрицы = -567.0000
Матрица не вырождена


## Проверка главных миноров

In [144]:
for i in range(matrix.shape[0] - 1):
    minor = matrix[:i+1, :i+1]
    if np.linalg.det(matrix) != 0:
        print(f'Минор M_{i+1}{i+1} не вырожден')
    else:
        print(f'Минор M_{i+1}{i+1} вырожден')
        print(f'M_{i+1}{i+1}:\n{str(minor)}')

Минор M_11 не вырожден
Минор M_22 не вырожден
Минор M_33 не вырожден


## LU-разложение

In [128]:
def lu_decomposition(matrix):
    lu = np.zeros(matrix.shape)
    n = shape[0]
    for i in range (n):
        for j in range(n):
            if i is 0:
                lu[i, j] = matrix[i, j]
                if j > i:
                    lu[j, i] = matrix[j, i] / lu[i, i]
            else:
                if j >= i:
                    vr = np.sum([lu[i, k] * lu[k, j] for k in range(i)])
                    lu[i, j] = matrix[i, j] - vr
                    
                if j >= i+1:
                    vr = np.sum([lu[j, k] * lu[k, i] for k in range(i)])
                    lu[j, i] = (matrix[j, i] - vr) / lu[i, i]
                    
    return lu

In [129]:
def get_L(lu):
    n = lu.shape[0]
    l = lu.copy()
    for i in range(n):
        for j in range(n):
            if i == j:
                l[i, j] = 1
            if j > i:
                l[i, j] = 0
    return l

def get_U(lu):
    n = lu.shape[0]
    u = lu.copy()
    for i in range(n):
        for j in range(n):
            if i > j:
                u[i, j] = 0
                
    return u

In [151]:
lu = lu_decomposition(matrix)

In [152]:
print("Исходная матрица A:\n" +
      str(matrix)
)
print("L:\n" +
      str(get_L(lu))
)
print("U:\n" +
      str(get_U(lu))
)
print("B = L x U - A\n" + 
      "B:\n" +
      str(np.matmul(get_L(lu), get_U(lu)) - matrix)
)

Исходная матрица A:
[[4 1 7 9]
 [6 0 9 6]
 [5 2 4 2]
 [4 6 7 5]]
L:
[[ 1.          0.          0.          0.        ]
 [ 1.5         1.          0.          0.        ]
 [ 1.25       -0.5         1.          0.        ]
 [ 1.         -3.33333333  0.90909091  1.        ]]
U:
[[  4.           1.           7.           9.        ]
 [  0.          -1.5         -1.5         -7.5       ]
 [  0.           0.          -5.5        -13.        ]
 [  0.           0.           0.         -17.18181818]]
B = L x U - A
B:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
